Add blogpost about readthedocs.org integration.
ComplianceAsCode/ComplianceAsCode.github.io pull request #16
Opened 2021-01-13 17:38 UTC by ggbecker

2021-01-14 18:10 UTC, matejak requested changes
There is a broken link, and I would suggest to copy-paste the rendered HTML to a Google doc to check for minor language issues.

Aside from that, I have provided some observations that are completely optional. This is a great and much-needed blog entry, thanks!

2021-01-14 18:10 UTC, matejak commented on _posts/2021-01-13-developer-documentation.md
> +`Read the Docs` is a documentation hosting platform which is Open Source and provides many ways to host your project's documentation. It mainly supports `Sphinx` format, but using additional plugins
I would move this section to the middle of Introduction.

2021-01-14 18:10 UTC, matejak commented on _posts/2021-01-13-developer-documentation.md
> +[ComplianceAsCode content project](https://github.com/ComplianceAsCode/content/) contains many documentation pieces spread all over the project, there is the [developer documentation}(https://github.
Curly brace breaks the HTML link syntax.

I would consider merging this section with the new one - one could distribute information from this paragraph to those individual points from the next paragraph.

2021-01-15 08:27 UTC, vojtapolasek commented on _posts/2021-01-13-developer-documentation.md
> +Each of them reflects the contents of their respective documentation present on [ComplianceAsCode content project](https://github.com/ComplianceAsCode/content/). Whatever change is made in the projec
I don't know if it makes sense to point two links in one paragraph to the content project. The whole blog post is about the project anyway.

2021-01-15 08:38 UTC, jan-cerny commented on _posts/2021-01-13-developer-documentation.md
> +Whether you are getting acquainted with the project or are a long term developer, this documentation transition to `Read the Docs` has brought many benefits for contributors. The documentation became
I feel it's repeating the benefits from the introduction. Instead, I would write something like "try it out now, add it to your bookmarks" (but using a better wording).

Otherwise your blog is amazing!

2021-01-15 12:42 UTC, ggbecker commented on _posts/2021-01-13-developer-documentation.md
> +Hosting the documentation on `Read the Docs` brings many benefits to the project. The documentation is easier to navigate, easier to search and it's better structured to support different documentati
Done.

2021-01-15 12:43 UTC, ggbecker commented on _posts/2021-01-13-developer-documentation.md
> +`Read the Docs` is a documentation hosting platform which is Open Source and provides many ways to host your project's documentation. It mainly supports `Sphinx` format, but using additional plugins
Done.

2021-01-15 12:45 UTC, ggbecker commented on _posts/2021-01-13-developer-documentation.md
> +[ComplianceAsCode content project](https://github.com/ComplianceAsCode/content/) contains many documentation pieces spread all over the project, there is the [developer documentation}(https://github.
Fixed.

And I've dissolved the paragraph but omitted some of the information here. Please check if it's ok.

2021-01-15 12:46 UTC, ggbecker commented on _posts/2021-01-13-developer-documentation.md
> +Each of them reflects the contents of their respective documentation present on [ComplianceAsCode content project](https://github.com/ComplianceAsCode/content/). Whatever change is made in the projec
I've removed every link to the project since it's already quite clear the connection between the blog and the project. Also the link is available in the footnote in all blog pages.

2021-01-15 12:47 UTC, ggbecker commented on _posts/2021-01-13-developer-documentation.md
> +Whether you are getting acquainted with the project or are a long term developer, this documentation transition to `Read the Docs` has brought many benefits for contributors. The documentation became
I tried to reformulate a bit here. I think it doesn't repeat stuff anymore and there are a couple of messages in the end to reflect your suggestions.

2021-01-15 13:05 UTC, jan-cerny commented
@ggbecker I like it

2021-01-18 14:16 UTC, matejak commented
Thanks for those changes. I have checked the post again, and there seems one thing worth mentioning that hasn't make it though - that would be the local build of the documentation for offline usage.

I think that it could even go to Conclusion.

2021-01-18 17:20 UTC, ggbecker commented
> Thanks for those changes. I have checked the post again, and there seems one thing worth mentioning that hasn't make it though - that would be the local build of the documentation for offline usage.
> 
> I think that it could even go to Conclusion.

I have added a small section before the conclusion talking about how to build locally. Please check again.

2021-01-19 15:08 UTC, matejak approved these changes

2021-01-19 15:08 UTC, matejak commented
Great, LGTM!

2021-01-19 15:09 UTC, merged