Post introducing the SSG Test Suite throught the approachable path.
ComplianceAsCode/ComplianceAsCode.github.io pull request #19
Opened 2021-03-12 10:49 UTC by matejak

This post aims to tell its readers just enough so they can quickly run a rule test, and that they have a rough idea what's going on to play with the test suite, examine test results, and maybe even add new test scenarios.

2021-03-15 07:41 UTC, jan-cerny requested changes
It's very clear and easy. I have only minor suggestions.

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +Testing of rules and remediations
```suggestion
Testing rules and remediations
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +As you can learn very quickly by visiting the [tests](https://github.com/ComplianceAsCode/content/tree/master/tests#readme) folder, the project features a test suite.
I got the idea and I appreciate your creativity but I somehow don't like it - the text talks about a folder, but after clicking on a link you are shown the readme, iow after clicking the reader gets a different thing than he expects. I suggest splitting this into 2 links.

```suggestion
As you can learn very quickly by visiting the [tests](https://github.com/ComplianceAsCode/content/tree/master/tests) folder, the project features a test suite.
The test suite is described in [README](https://github.com/ComplianceAsCode/content/blob/master/tests/README.md) located in this directory.
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +The project already contains predefined recipes, so let's leverage them, and build the test container:
Recipes? I think you meant "tools to set up test environment".

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +1. The applicability of the datastream is extended to include the system used for the actual test - in this case Fedora.
Do you recommend testing data streams for other platforms on different platforms? Isn't testing on the same platform the best practice? I assume you will get worng results in case of rules that differ between platforms.

Can you add more text about this topic?

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +Let's look a completely different scenario [missing.fail.sh](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/tests/missing.fail.
```suggestion
Let's look at a completely different scenario [missing.fail.sh](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/tests/missing.fail.sh) - for the [grub2_password](https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password) rule - and check its contents:
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +It can test profiles, when it can determine how "green" can the datastream make typically a freshly installed system.
```suggestion
It can test profiles, when it can determine how "green" can the data stream make typically a freshly installed system.
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +... and we have the datastream!
```suggestion
... and we have the data stream!
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +The content still corresponds to the system that the datastream has been compiled for, in this case that would be the RHEL7 content, but it could be SLE or Ubuntu content as well.
```suggestion
The content still corresponds to the system that the data stream has been compiled for, in this case that would be the RHEL7 content, but it could be SLE or Ubuntu content as well.
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +A virtual machine feels much closer to the bare-metal, and the test suite supports the `libvirt` backend, which leverages all those snapshots and VM control capabilities of `libvirt` to execute tests
```suggestion
A virtual machine feels much closer to the bare-metal, and the test suite supports the `libvirt` backend which leverages VM control capabilities of `libvirt` to execute tests.
```

2021-03-15 07:41 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +First of all, we will need a test environment.
Do I have to have some packages installed on my machine before I can run this?

2021-03-15 08:09 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +$ tests/test_rule_in_container.sh --dontclean accounts_tmout
`--dontclean` doesn't exist

2021-03-15 08:19 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +$ tests/test_rule_in_container.sh --dry-run --dontclean accounts_tmout
`--dry-run --dontclean` doesn't exist

2021-03-15 08:20 UTC, jan-cerny commented on _posts/2021-03-15-tests_howto.md
> +$ tests/test_rule_in_container.sh --dry-run --dontclean accounts_tmout
Aha I can see there is a PR. https://github.com/ComplianceAsCode/content/pull/6675/files

2021-03-25 12:25 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +First of all, we will need a test environment.
I think for container backend you only need podman to be installed.

2021-03-25 12:41 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +3. Remediation - in case of `oscap` remediation, this step includes the final scan as well.
AFAIK, It should be the same for `ansible` and `bash`. In case of ansible you need ansible package installed.

2021-03-25 13:12 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +As you can learn very quickly by visiting the [tests](https://github.com/ComplianceAsCode/content/tree/master/tests#readme) folder, the project features a test suite.
incorporated

2021-03-25 13:13 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +The project already contains predefined recipes, so let's leverage them, and build the test container:
accepted the suggestion with a slight change

2021-03-25 13:13 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +Let's look a completely different scenario [missing.fail.sh](https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/tests/missing.fail.
done

2021-03-25 13:13 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +... and we have the datastream!
I don't think we need to change all the occurrences of `datastream`

2021-03-25 13:14 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +A virtual machine feels much closer to the bare-metal, and the test suite supports the `libvirt` backend, which leverages all those snapshots and VM control capabilities of `libvirt` to execute tests
incorporated

2021-03-25 13:14 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +First of all, we will need a test environment.
only podman for container testing, it should be already installed (the post is assuming that I guess)

2021-03-25 13:18 UTC, ggbecker commented on _posts/2021-03-15-tests_howto.md
> +1. The applicability of the datastream is extended to include the system used for the actual test - in this case Fedora.
This was the only thing I have not touched. I don't think it should be a blocker for the blog post. I think it was clear enough that this is just to make starting of tests easier and the appropriate machine/container should be used to serious testing.

2021-03-25 13:20 UTC, ggbecker approved these changes
I have reviewed and edited the blog post. LGTM.

2021-03-25 13:20 UTC, merged