Collect notable improvements of the 0.1.58 release
ComplianceAsCode/ComplianceAsCode.github.io pull request #25
Opened 2021-09-10 16:02 UTC by matejak

2021-09-24 08:52 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +More information is found in the [development documentation](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html).
```suggestion
### Development environment setup via Ansible

We now have an Ansible role to help us to very quickly prepare a completely functional development environment. About 10 minutes are enough for Ansible to safely conclude the hard work and deliver a ready to go development environment.

This is a great option to start contributing faster, aligned with the official documentation and enjoying the automation benefits. : )

More information is found in the [development documentation](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html).
```

Couple of suggestions

2021-09-24 08:54 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +The first mechanism are the [bash_remediation_functions](https://github.com/ComplianceAsCode/content/tree/v0.1.57/shared/bash_remediation_functions).
```suggestion
The first mechanism is the [bash_remediation_functions](https://github.com/ComplianceAsCode/content/tree/v0.1.57/shared/bash_remediation_functions).
```

2021-09-24 08:54 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +A mechanism that makes use of the XCCDF substitution capability to inject the Bash function into the remediations, this means that OpenSCAP is used to make the substituions and render the final remed
```suggestion
A mechanism that makes use of the XCCDF substitution capability to inject the Bash function into the remediations, this means that OpenSCAP is used to make the substitutions and render the final remediation snippet.
```

2021-09-24 08:56 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +The second mechanism are the [Jinja macros](https://github.com/ComplianceAsCode/content/blob/v0.1.57/shared/macros-bash.jinja), which are expanded during the content build.
```suggestion
The second mechanism is the [Jinja macros](https://github.com/ComplianceAsCode/content/blob/v0.1.57/shared/macros-bash.jinja), which are expanded during the content build.
```

2021-09-24 08:57 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +In this release a good portion of the Bash remediation functions were transformed into Jinja macros, and by next release all of them will have been moved up to macros.
```suggestion
In this release a good portion of the Bash remediation functions were transformed into Jinja macros, and by the next release all of them will be turned into macros.
```

2021-09-24 08:58 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +The expansion of the snippets at build time will provide more clarity on the final remediation;
```suggestion
The expansion of snippets at build time will provide more clarity on the final remediation;
```

2021-09-24 09:19 UTC, yuumasato reviewed
Pushed ac571d4 with a few fixes.

2021-09-24 09:19 UTC, yuumasato commented on _posts/2021-09-31-release-0.1.58.md
> +More information is found in the [development documentation](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html).
@ggbecker It is not clear what the suggestion is changing.

2021-09-24 09:19 UTC, yuumasato commented on _posts/2021-09-31-release-0.1.58.md
> +In this release a good portion of the Bash remediation functions were transformed into Jinja macros, and by next release all of them will have been moved up to macros.
@ggbecker I think the use of future perfect is correct.

2021-09-24 09:33 UTC, yuumasato commented on _posts/2021-09-31-release-0.1.58.md
> +In this release a good portion of the Bash remediation functions were transformed into Jinja macros, and by next release all of them will have been moved up to macros.
It is actually passive future perfect. https://www.englishreservoir.com/all-passive-forms/future-perfect-3/

2021-09-24 09:45 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +More information is found in the [development documentation](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html).
All right, I had some changes here but then I switched to a different page and I lost my suggestions... let me redo it :(

2021-09-24 09:56 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +In this release a good portion of the Bash remediation functions were transformed into Jinja macros, and by next release all of them will have been moved up to macros.
got it ;)

2021-09-24 12:47 UTC, marcusburghardt commented on _posts/2021-09-31-release-0.1.58.md
> +More information is found in the [development documentation](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html).
Thanks for the fine adjusts @ggbecker

2021-09-30 11:57 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +By default, the content is built without SCE checks, check [Building SCE](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html?highlight=SCE#building-s
```suggestion
By default, the content is built without SCE checks, check [Building SCE](https://complianceascode.readthedocs.io/en/latest/manual/developer/02_building_complianceascode.html#building-sce-non-compliant-content) section in the docs, for
```

2021-09-30 11:58 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +Note that content built with SCE checks are not SCAP compliant.
```suggestion
Note that content built with SCE checks is not SCAP compliant.
```

2021-09-30 11:58 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +Notable new profiles in this release:
```suggestion
Notable new profiles added in this release:
```

2021-09-30 12:56 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +### Sorting of references and identifiers
We are still missing this section text, should we drop it? @matejak @yuumasato

2021-09-30 12:59 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +This is a great option to start contributing faster, aligned with the official documentation while enjoying the automation benefits. : )
```suggestion
This is a great option to start contributing faster, aligned with the official documentation while enjoying the automation benefits.
```

2021-09-30 13:04 UTC, ggbecker requested changes
we also need to change the name of the file to something else than 31 september (which doesn't exist) for example: 2021-09-3**0**-release-0.1.58.md

2021-09-30 13:30 UTC, yuumasato commented on _posts/2021-09-31-release-0.1.58.md
> +### Sorting of references and identifiers
I can look into it.

2021-09-30 14:21 UTC, yuumasato commented on _posts/2021-09-31-release-0.1.58.md
> +### Sorting of references and identifiers
Added in e01bf5c

2021-09-30 14:47 UTC, matejak commented on _posts/2021-09-31-release-0.1.58.md
> +### Sorting of references and identifiers
I have asked @Mab879 to give it a thought.

2021-09-30 15:05 UTC, ggbecker commented on _posts/2021-09-30-release-0.1.58.md
> +The rules in the project can reference security policy requirements to indicate that they implement or support them, and be assigned identifiers to uniqueily identify a configuration item within a pr
```suggestion
The rules in the project can reference security policy requirements to indicate that they implement or support them, and be assigned identifiers to uniquely identify a configuration item within a product.
```

2021-09-30 15:07 UTC, ggbecker commented on _posts/2021-09-31-release-0.1.58.md
> +### Sorting of references and identifiers
I'm ok with current text provided by @yuumasato in e01bf5c

2021-09-30 15:24 UTC, ggbecker approved these changes
LGTM, verified locally on jekyll, no issues with rendering.

2021-09-30 15:24 UTC, merged