Add a MRAC preview post
ComplianceAsCode/ComplianceAsCode.github.io pull request #58
Opened 2023-04-18 13:37 UTC by matejak

Add a post that can serve as a teaser, and discussion starter for enhancements that part of the community would like to deliver in order to make the build system more capable/flexible.
The point of the post is to encourage discussion early, and to help to see upcoming PRs (at least we hope that they will come :-) in a greater context.

2023-04-18 13:57 UTC, jan-cerny requested changes

2023-04-18 13:57 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +If we think in a very simple way, we clearly need to design smart procedures or workflows that recact to changes, so no major brain power is needed to make right decisions.
recact

2023-04-18 14:24 UTC, jan-cerny requested changes
In general, the blog post is difficult to read and understand.

It isn't clear whether it describes existing features or proposes some future features.

Please focus on clarity. You can help yourself by adding specific examples to the text.

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +Our Red Hat group is contemplating the idea of making the content project better equipped to handle changes in component behavior better.
s/component/software/

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +This could be achieved by set of rules with disjoint applicability, and the recently-introduced CPE Applicability Language helps this.
demonstrate this on an example

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +In practice, if we don't know at build-time what component will be scanned, we may solve this by having multiple rules ready.
not ready but having multiple rules where each rule is for a different version of the examined software

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +And perhaps there are other examples of redundant data?
Confusing. What are you trying to describe? I would recommend using templates and Jinja macros.

Demonstrate this on an example so that the readers can imagine it.

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +Designing product properties in a way that is smart, doesn't get in the way and that can be reused in prose, checks and remediations is not trivial.
Please reword it that you recommend using product properties. Please add a working example.

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +This can be very difficult to achieve exhaustively, but partial/good enough achievement may be actually doable.
Is this a proposal for a future feature? If yes, introduce it as such and be more specific.

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +
example missing

2023-04-18 14:24 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +If things go ahead as planned, you may expect pull requests showing up in upcoming months, and we are very much interested in your point of view.
What will these PRs introduce?

2023-04-20 15:19 UTC, matejak commented on _posts/2023-04-21-mrac.md
> +Our Red Hat group is contemplating the idea of making the content project better equipped to handle changes in component behavior better.
Software is a too generic term, and I find component fitting.
I have added a description of what a component is, did it help?

2023-04-20 15:20 UTC, matejak commented on _posts/2023-04-21-mrac.md
> +If things go ahead as planned, you may expect pull requests showing up in upcoming months, and we are very much interested in your point of view.
Nobody knows now, so we have to wait for them with great anticipation.

2023-04-20 15:23 UTC, matejak commented on _posts/2023-04-21-mrac.md
> +This can be very difficult to achieve exhaustively, but partial/good enough achievement may be actually doable.
A proposal will be introduced properly in the PR that implements it. This post just aims to shift attention to some gaps in the project, and to potential solutions that nobody knows right now.

2023-04-20 15:23 UTC, matejak commented on _posts/2023-04-21-mrac.md
> +In practice, if we don't know at build-time what component will be scanned, we may solve this by having multiple rules ready.
reworded (differently), hopefully good enough.

2023-04-24 09:48 UTC, jan-cerny reviewed
I like the improvements from the previous version.

I only have minor style and grammar suggestions.

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +For example, the Red Hat Enterprise Linux consists of more than six thousand of such distinct components, although only a fraction of them s.a. OpenSSH, Grub2 and so on is supported by the Compliance
either such as or and so on but never both

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +###  Be able to track component changes and our reactions to them.
remove the dot

Change "Be able" to "Ability"

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +- Be able to split a rule into such a set of rules easily.
```suggestion
- Be able to split a rule into a set of rules easily.
```

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +In practice, we may not know at build-time what exact version of a component will be scanned, and we may address this uncertainty by having multiple rules prepared to handle this uncertainty.
repeating uncertainity

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +We often use constructs s.a. `{{% if product in ("rhel8", "rhel9") %}}` instead of a more generic and understandable `{{% if product.prefers_single_file_sshd_configuration %}}` or something analogous
```suggestion
We often use constructs s.a. `{{% if product in ("rhel8", "rhel9") %}}` instead of a more generic and understandable `{{% if product.prefers_single_file_sshd_configuration %}}` or similar.
```

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +We have some polymorphic rules in our content, but they became polymorphic on their own, the project hasn't helped them with their polymorphism.
little cumbersome

2023-04-24 09:48 UTC, jan-cerny commented on _posts/2023-04-21-mrac.md
> +Project support for polymorphism of rules could reduce maintenance costs, as polymorphism would become more declarative.
```suggestion
Adding support for polymorphism of rules could reduce maintenance costs, as polymorphism would become more declarative.
```

2023-04-25 06:26 UTC, jan-cerny approved these changes

2023-04-25 06:26 UTC, merged